# Use the official PostgreSQL image
FROM postgres:13

# Set environment variables for PostgreSQL
ENV POSTGRES_USER='sabiha'
ENV POSTGRES_PASSWORD='sabiha123'
ENV POSTGRES_DB='my_database'




# Expose PostgreSQL port
EXPOSE 5432