version: '3'

services:
  app:
    build:
      context: ../backEnd/  # Directory where the Dockerfile is located
      dockerfile: Dockerfile  # The name of your Dockerfile (change if necessary)
    image: my_stackoverflow_image
    container_name: my_stackoverflow_container  # Customize container name
    ports:
      - "3000:5001"  # Maps host port 3000 to container port 3000
      - "4000:5001"  # Maps host port 3000 to container port 3000
    environment:
      - NODE_ENV=development  # Example environment variable
    # volumes:
    #   - ../backEnd:/app  # Mounts the current directory to /app in the container
    # Mount the current directory to the container
    depends_on:
      - db  # Ensure db service starts before app

  # This is for Docker.db file(run database through Dockerfile.db and docker-compose.yml )

  db:
    build:
      context: ../backEnd/
      dockerfile: Dockerfile.db
    image: stackoverflow_postgres_db  # Example database (replace with another if needed)
    container_name: my_database_container
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: 'sabiha'
      POSTGRES_PASSWORD: 'sabiha123'
      POSTGRES_DB: 'my_database'
    volumes:
      - db_data:/var/lib/postgresql/data  # Persist database data

volumes:
  db_data:


 